### PR TITLE
corrigindo tratamento de erro preapproval

### PR DESCRIPTION
**Pull request by felipeminello**
Corrigindo tratamento de erro, ao tentar fazer uma nova assinatura de plano

Erro:
```
{
    "message": "Undefined index: error",
    "exception": "ErrorException",
    "file": "/home/minello/projects/adorofotos/vendor/mercadopago/dx-php/src/MercadoPago/Entity.php",
    "line": 275
}
```

### CODE REVIEW

**Review by gabrielbitti — APPROVED** [review]

**Review by orijmm — APPROVED** [review]
Tested and worked.

Testedo y funciona

**Comment by orijmm** [comment]
Funciona

**Comment by rhames07** [comment]
Hey!

Thanks in advance for your contribution.

I am validating the PR and I tried to save an invalid Pre-Approval object but the error does not reproduce.
In my case, if `message["error"]` is null, it will be set to NULL in `RecuperableError` exception and `ErrorException` will not be thrown.

My test (not reproducing error):
```php
$preapproval = new MercadoPago\Preapproval();
$preapproval->save("aaa");
```

Could you inform the steps used to reproduce the error?

Thanks :)

**Comment by orijmm** [comment]
Hi!

if $preapproval_data->payer_email  = "test@gmail.com";  does not have a mercadopago account

**Comment by rhames07** [comment]
@orijmm Can you send me the entire snippet? Still not reproducing the error here :(

**Comment by orijmm** [comment]
\MercadoPago\SDK::setAccessToken($payment->key_secret);
            $preapproval_data = new \MercadoPago\Preapproval();

            $preapproval_data->payer_email = $user->email;
            $preapproval_data->back_url = "https://www.mercadopago.cl/";
            $preapproval_data->reason = "suscripción por: ";
            $preapproval_data->external_reference = trans('general.subscription_for').' @'.$user->username.' - '.$plan->name;
            $preapproval_data->auto_recurring = array( 
                "frequency" => 1,
                "frequency_type" => "months",
                "transaction_amount" => "800",
                "currency_id" => "CLP"
            );

            $preapproval_data->save();

**Comment by rhames07** [comment]
We will merge this PR and release a new version as soon as possible.
Thank you for your collaboration and for using the MercadoPago SDK. :)

**Pull request merged**
